apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/vendir/vsphere_cpi/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 0fa3055c5cddf67f8c23edea420575cb4eb7d5d8
    includePaths:
    - addons/packages/vsphere-cpi/1.22.5/bundle/config/**/*
- path: ytt/vendir/cni/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: bbc123db82e9bf07ef3472c5e335317c392d9d31
    includePaths:
    - addons/packages/antrea/1.5.2/bundle/config/**/*
    - addons/packages/calico/3.22.1/bundle/config/**/*
- path: ytt/vendir/kapp-controller/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 5e43d627bdd25ebca3f5c30ce72331f1543a0eba
    includePaths:
<<<<<<< HEAD
    - addons/packages/kapp-controller/0.38.3/bundle/config/**/*
=======
    - addons/packages/kapp-controller/0.34.0/bundle/config/**/*
>>>>>>> add http proxy and replica values
- path: ytt/vendir/csi/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 01aacda03bf9e49bce0ddafc1d98ceffaa20fd8e
    includePaths:
    - addons/packages/aws-ebs-csi-driver/1.8.0/bundle/config/**/*
    - addons/packages/azuredisk-csi-driver/1.19.0/bundle/config/**/*
