#@ load("/values.star", "values")
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name": "ebs-csi-controller"}})
---
kind: Deployment
metadata:
  name: ebs-csi-controller
spec:
  template:
    spec:
      #@overlay/replace
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule